### ISSUE TITLE
Expected to work outside of Doom?

### ISSUE THREAD

**Issue by nrvale0** [ronisbr/doom-nano-modeline#1]
Howdy. These look pretty nice. :)

Are they expected to work with vanilla emacs/outside of Doom? I have various other doom-*-themes packages I use with success but these throw a message that they have failed to load. Before I dive in to see if I can determine why I first wanted to check expectations.

thx

**Comment by ronisbr** [comment]
Hi @nrvale0 !

Thanks! It should work, but I did not test it. If you see some problem let me know please. It should not be difficult to adapt to avoid doom dependency.

**Comment by nrvale0** [comment]
Thx for confirming. Not an elisp hacker per se but I'll see if I can figure it out.
