### ISSUE TITLE
Is there a method to show coding system and input method? 

### ISSUE THREAD

**Issue by shartf** [ronisbr/doom-nano-modeline#3]
Hi, 

I understand that this topic is maybe better to be addressed upstream, but is there a method to display Input method and coding system in the modeline? Coding system is not that interesting since almost everything is utf8 these days, but input method is pretty important for people who more than one keyboard layout.

Showing abbreviations indicated as `A` in the wiki would already be sufficient, I think, and since in non-evil keybindings there anyway a place unused in the left corner of the modeline, it could be placed there...
https://www.emacswiki.org/emacs/ModeLine

**Comment by koiuo** [comment]
I'd like to see input mode in this modeline too.
If not implemented out of the box, at least some guidance in how to add would be really helpful.

**Comment by ronisbr** [comment]
Hi! Sorry, I completely forgot about this request :(

Currently, there is no "easy" way. I will see how I can extend the API to allow people to add custom information.

**Comment by martinbaillie** [comment]
This would be great! I love the modeline I just want to add a bit more info (flycheck/lsp).

**Comment by ronisbr** [comment]
Hi! Sorry for the delay. With the new version, we can add any information in the right side (to the left of the cursor position). Hence, each user can customize it to add the information they want by providing a function as stated in the README. I hope it can fix this issue!
